[project]
name = "ring-standard"
authors = ["Ring Protocol Team"]
description = "Decentralized identity verification protocol"
telemetry = false
requirements = []
[contracts.ring-core]
path = "contracts/ring-core.clar"
depends_on = []

[contracts.ring-exchange]
path = "contracts/ring-exchange.clar"
depends_on = []

[contracts.ring-network]
path = "contracts/ring-network.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
